import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      include: ["src/**"],
      exclude: [
        "src/**/*.test.ts",
        "src/test-utils.ts",
        // Vendored Kontor contract bindings — machine-generated by kontor-codegen.
        "src/kontor/__generated__/**",
      ],
    },
  },
});
