import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      include: ["src/**"],
      exclude: [
        "src/**/*.test.ts",
        "src/test-utils.ts",
        // Vendored Kontor contract bindings — machine-generated by kontor-codegen.
        "src/kontor/__generated__/**",
        // Pure-presentation React UI: rendered components (web + native), style
        // and theme tokens, icon paths, and re-export barrels. These carry no
        // branching logic worth unit-testing for coverage — they are exercised
        // by the example apps / e2e. Coverage here measures the framework-
        // agnostic SDK core plus the React adapter's real logic (hooks,
        // controllers, and pure helpers), which is where correctness lives.
        "src/react/**/*.tsx",
        "src/react/**/*.native.ts", // index.native barrel + styles.native tokens
        "src/react/index.web.ts", // web re-export barrel
        "src/react/hooks/index.ts", // hooks re-export barrel
        "src/swaps/index.ts", // WASM-free swaps re-export barrel
        "src/react/internal/styles.web.ts", // style token map
        "src/react/internal/useMediaQuery.web.ts", // matchMedia browser shim
        "src/react/theme.ts", // theme tokens
      ],
    },
  },
});
