// Generated by kontor-codegen. Do not edit by hand.
import { Wit, ContractBase, type ContractAddress, type Inst, type KontorSession, HolderRef, Attachment } from "@kontor/sdk";

export type Error = { kind: "message"; value: string } | { kind: "overflow"; value: string } | { kind: "div-by-zero"; value: string } | { kind: "syntax"; value: string } | { kind: "validation"; value: string };

export type RawFileDescriptor = {
  fileId: string;
  objectId: string;
  nonce: Array<number>;
  root: Array<number>;
  paddedLen: bigint;
  originalSize: bigint;
  filename: string;
};

export type NftInfo = {
  nftId: string;
  owner: HolderRef;
  creator: HolderRef;
  agreementId: string;
};

export type NftTransfer = {
  nftId: string;
  src: HolderRef;
  dst: HolderRef;
};

export type Attribute = {
  key: string;
  value: string;
};

const WIT = String.raw`package root:component;

world root {
  include kontor:built-in/built-in;
  use kontor:built-in/context.{holder-ref, view-context, proc-context, contract};
  use kontor:built-in/error.{error};
  use kontor:built-in/file-registry.{raw-file-descriptor};

  record nft-info {
    nft-id: string,
    owner: holder-ref,
    creator: holder-ref,
    agreement-id: string,
  }

  record nft-transfer {
    nft-id: string,
    src: holder-ref,
    dst: holder-ref,
  }

  record attribute {
    key: string,
    value: string,
  }

  export init: async func(ctx: borrow<proc-context>) -> contract;

  /// Mint a new NFT backed by a filestorage agreement created from \`file-descriptor\`.
  ///
  /// Validation rules enforced by the contract:
  /// - \`nft-id\` must be non-empty and at most 64 bytes (UTF-8 length, no
  ///   trim, case-sensitive, globally unique across all NFTs in this contract).
  /// - \`attributes\` describe the NFT as an immutable map of string-to-string
  ///   pairs (set once at mint, never updated afterwards). The list must
  ///   contain at most 32 entries; every \`key\` must be non-empty and at most
  ///   64 bytes; every \`value\` must be at most 2048 bytes; keys must be
  ///   unique within the list (duplicate keys cause \`mint\` to fail).
  /// - \`file-descriptor.file-id\` is freely chosen by the caller and validated
  ///   by \`filestorage::create-agreement\` (non-empty, etc.); it shares its
  ///   global namespace with all other agreements but is decoupled from
  ///   \`nft-id\`.
  ///
  /// On success the returned \`agreement-id\` is the agreement id created by
  /// filestorage (which equals \`file-descriptor.file-id\`) and is stored
  /// alongside the NFT as a link to the underlying file.
  export mint: async func(
    ctx: borrow<proc-context>,
    nft-id: string,
    attributes: list<attribute>,
    file-descriptor: raw-file-descriptor
  ) -> result<nft-info, error>;

  export transfer: async func(
    ctx: borrow<proc-context>,
    nft-id: string,
    new-owner: holder-ref
  ) -> result<nft-transfer, error>;

  export attach: async func(
    ctx: borrow<proc-context>,
    nft-id: string,
    vout: u32
  ) -> result<nft-transfer, error>;

  export detach: async func(
    ctx: borrow<proc-context>,
    nft-id: string
  ) -> result<nft-transfer, error>;

  export get-info: async func(ctx: borrow<view-context>, nft-id: string) -> option<nft-info>;
  export total-minted: async func(ctx: borrow<view-context>) -> u64;

  /// Return up to \`limit\` minted NFTs, skipping the first \`offset\` entries.
  ///
  /// Use this together with \`total-minted\` to paginate through the full
  /// collection. The iteration order matches the underlying storage map
  /// (lexicographic on \`nft-id\`) and is stable as long as the store is
  /// not mutated between calls.
  ///
  /// \`limit\` is silently clamped to an internal cap (currently 100) to
  /// keep response sizes predictable; pass \`limit = 0\` for an empty
  /// page. \`offset\` beyond the collection size yields an empty list.
  export list-nfts: async func(
    ctx: borrow<view-context>,
    offset: u64,
    limit: u64
  ) -> list<nft-info>;

  /// Return up to \`limit\` NFTs originally minted by \`creator\`, skipping
  /// the first \`offset\` matches. Backed by a secondary creator→nft-ids
  /// index that is populated at \`mint\` and never mutated afterwards
  /// (transfers do not move NFTs across creator buckets), so the cost
  /// is proportional to \`offset + limit\`.
  ///
  /// "Creator" is the signer of the \`mint\` call that produced the NFT;
  /// it is immutable for the lifetime of the NFT and is also exposed on
  /// \`nft-info.creator\`. This is the right query for "what did this
  /// account ever mint?", which is independent of who owns the NFTs
  /// today.
  ///
  /// The same clamping rules as \`list-nfts\` apply (\`limit\` is capped at
  /// an internal maximum, \`limit = 0\` returns an empty list, and an
  /// \`offset\` beyond the creator's collection yields an empty list). The
  /// iteration order matches the underlying storage map (lexicographic
  /// on \`nft-id\`) and is stable between calls as long as the store is
  /// not mutated. An invalid or never-seen \`creator\` yields an empty
  /// list rather than an error.
  export list-nfts-by-creator: async func(
    ctx: borrow<view-context>,
    creator: holder-ref,
    offset: u64,
    limit: u64
  ) -> list<nft-info>;

  /// Number of NFTs minted by \`creator\`. Equivalent to the length of
  /// the full (non-paginated) \`list-nfts-by-creator\` result. Returns 0
  /// when \`creator\` has no entry in the index.
  export count-nfts-by-creator: async func(
    ctx: borrow<view-context>,
    creator: holder-ref
  ) -> u64;

  /// Return up to \`limit\` NFTs currently held by \`holder\`, skipping the first
  /// \`offset\` matches. Backed by an append-only holder→nft-ids index populated
  /// on every ownership change (\`mint\`, \`transfer\`, \`attach\`, \`detach\`); ids a
  /// holder has since transferred away linger in the index and are filtered out
  /// here by re-checking current ownership, so the result always reflects who
  /// owns the NFTs today.
  ///
  /// The same clamping rules as \`list-nfts\` apply. An invalid or never-seen
  /// \`holder\` yields an empty list rather than an error.
  export list-nfts-by-holder: async func(
    ctx: borrow<view-context>,
    holder: holder-ref,
    offset: u64,
    limit: u64
  ) -> list<nft-info>;

  /// Number of NFTs currently held by \`holder\`. O(1). Returns 0 for unknown holders.
  export count-nfts-by-holder: async func(
    ctx: borrow<view-context>,
    holder: holder-ref
  ) -> u64;

  export get-attributes: async func(ctx: borrow<view-context>, nft-id: string) -> list<attribute>;
  export get-attribute: async func(ctx: borrow<view-context>, nft-id: string, key: string) -> option<string>;
}
`;
const _wit = new Wit(WIT);

function _encodeT0(v: Array<number>): unknown { return v.map(x => x); }
function _decodeT0(v: unknown): Array<number> { return (v as unknown[]).map(x => x as number); }
function _encodeError(v: Error): unknown { switch (v.kind) { case "message": return { kind: "message", value: (v as any).value }; case "overflow": return { kind: "overflow", value: (v as any).value }; case "div-by-zero": return { kind: "div-by-zero", value: (v as any).value }; case "syntax": return { kind: "syntax", value: (v as any).value }; case "validation": return { kind: "validation", value: (v as any).value }; default: throw new Error("unknown variant case: " + (v as any).kind); } }
function _decodeError(v: unknown): Error { switch ((v as any).kind) { case "message": return { kind: "message", value: (v as any).value } as Error; case "overflow": return { kind: "overflow", value: (v as any).value } as Error; case "div-by-zero": return { kind: "div-by-zero", value: (v as any).value } as Error; case "syntax": return { kind: "syntax", value: (v as any).value } as Error; case "validation": return { kind: "validation", value: (v as any).value } as Error; default: throw new Error("unknown variant case: " + (v as any).kind); } }
function _encodeRawFileDescriptor(v: RawFileDescriptor): unknown { return { "file-id": v.fileId, "object-id": v.objectId, "nonce": _encodeT0(v.nonce), "root": _encodeT0(v.root), "padded-len": v.paddedLen.toString(), "original-size": v.originalSize.toString(), "filename": v.filename }; }
function _decodeRawFileDescriptor(v: unknown): RawFileDescriptor { return { fileId: (v as any)["file-id"], objectId: (v as any)["object-id"], nonce: _decodeT0((v as any)["nonce"]), root: _decodeT0((v as any)["root"]), paddedLen: BigInt((v as any)["padded-len"] as string), originalSize: BigInt((v as any)["original-size"] as string), filename: (v as any)["filename"] }; }
function _encodeNftInfo(v: NftInfo): unknown { return { "nft-id": v.nftId, "owner": (v.owner).toRaw(), "creator": (v.creator).toRaw(), "agreement-id": v.agreementId }; }
function _decodeNftInfo(v: unknown): NftInfo { return { nftId: (v as any)["nft-id"], owner: HolderRef.fromRaw((v as any)["owner"] as any), creator: HolderRef.fromRaw((v as any)["creator"] as any), agreementId: (v as any)["agreement-id"] }; }
function _encodeNftTransfer(v: NftTransfer): unknown { return { "nft-id": v.nftId, "src": (v.src).toRaw(), "dst": (v.dst).toRaw() }; }
function _decodeNftTransfer(v: unknown): NftTransfer { return { nftId: (v as any)["nft-id"], src: HolderRef.fromRaw((v as any)["src"] as any), dst: HolderRef.fromRaw((v as any)["dst"] as any) }; }
function _encodeAttribute(v: Attribute): unknown { return { "key": v.key, "value": v.value }; }
function _decodeAttribute(v: unknown): Attribute { return { key: (v as any)["key"], value: (v as any)["value"] }; }
function _encodeT88(v: Array<Attribute>): unknown { return v.map(x => _encodeAttribute(x)); }
function _decodeT88(v: unknown): Array<Attribute> { return (v as unknown[]).map(x => _decodeAttribute(x)); }
function _encodeT89(v: { kind: "ok"; value: NftInfo } | { kind: "err"; value: Error }): unknown { return v.kind === "ok" ? { kind: "ok", value: _encodeNftInfo(v.value) } : { kind: "err", value: _encodeError(v.value) }; }
function _decodeT89(v: unknown): { kind: "ok"; value: NftInfo } | { kind: "err"; value: Error } { return (v as any).kind === "ok" ? { kind: "ok" as const, value: _decodeNftInfo((v as any).value) } : { kind: "err" as const, value: _decodeError((v as any).value) }; }
function _encodeT90(v: { kind: "ok"; value: NftTransfer } | { kind: "err"; value: Error }): unknown { return v.kind === "ok" ? { kind: "ok", value: _encodeNftTransfer(v.value) } : { kind: "err", value: _encodeError(v.value) }; }
function _decodeT90(v: unknown): { kind: "ok"; value: NftTransfer } | { kind: "err"; value: Error } { return (v as any).kind === "ok" ? { kind: "ok" as const, value: _decodeNftTransfer((v as any).value) } : { kind: "err" as const, value: _decodeError((v as any).value) }; }
function _encodeT92(v: NftInfo | null): unknown { return v == null ? null : _encodeNftInfo(v); }
function _decodeT92(v: unknown): NftInfo | null { return v == null ? null : _decodeNftInfo(v); }
function _encodeT93(v: Array<NftInfo>): unknown { return v.map(x => _encodeNftInfo(x)); }
function _decodeT93(v: unknown): Array<NftInfo> { return (v as unknown[]).map(x => _decodeNftInfo(x)); }
function _encodeT94(v: string | null): unknown { return v == null ? null : v; }
function _decodeT94(v: unknown): string | null { return v == null ? null : v as string; }
function _encodeT95(v: unknown): unknown { return v; }
function _decodeT95(v: unknown): unknown { return v as unknown; }

export class Contract extends ContractBase {
  constructor(session: KontorSession, address: ContractAddress) {
    super(session, address, _wit);
  }

  init(): Inst<unknown> {
    return this._proc("init", {  }, (raw: unknown) => _decodeT95(raw));
  }

  mint(nftId: string, attributes: Array<Attribute>, fileDescriptor: RawFileDescriptor): Inst<{ kind: "ok"; value: NftInfo } | { kind: "err"; value: Error }> {
    return this._proc("mint", { "nft-id": nftId, "attributes": _encodeT88(attributes), "file-descriptor": _encodeRawFileDescriptor(fileDescriptor) }, (raw: unknown) => _decodeT89(raw));
  }

  transfer(nftId: string, newOwner: HolderRef): Inst<{ kind: "ok"; value: NftTransfer } | { kind: "err"; value: Error }> {
    return this._proc("transfer", { "nft-id": nftId, "new-owner": (newOwner).toRaw() }, (raw: unknown) => _decodeT90(raw));
  }

  attachment(nftId: string): Attachment<{ kind: "ok"; value: NftTransfer } | { kind: "err"; value: Error }> {
    return this._attachment(
      "attach", { "vout": 0, "nft-id": nftId },
      "detach", { "nft-id": nftId },
      (raw: unknown) => _decodeT90(raw),
    );
  }

  getInfo(nftId: string): Promise<NftInfo | null> {
    return this._view("get-info", { "nft-id": nftId }, (raw: unknown) => _decodeT92(raw));
  }

  totalMinted(): Promise<bigint> {
    return this._view("total-minted", {  }, (raw: unknown) => BigInt(raw as string));
  }

  listNfts(offset: bigint, limit: bigint): Promise<Array<NftInfo>> {
    return this._view("list-nfts", { "offset": offset.toString(), "limit": limit.toString() }, (raw: unknown) => _decodeT93(raw));
  }

  listNftsByCreator(creator: HolderRef, offset: bigint, limit: bigint): Promise<Array<NftInfo>> {
    return this._view("list-nfts-by-creator", { "creator": (creator).toRaw(), "offset": offset.toString(), "limit": limit.toString() }, (raw: unknown) => _decodeT93(raw));
  }

  countNftsByCreator(creator: HolderRef): Promise<bigint> {
    return this._view("count-nfts-by-creator", { "creator": (creator).toRaw() }, (raw: unknown) => BigInt(raw as string));
  }

  listNftsByHolder(holder: HolderRef, offset: bigint, limit: bigint): Promise<Array<NftInfo>> {
    return this._view("list-nfts-by-holder", { "holder": (holder).toRaw(), "offset": offset.toString(), "limit": limit.toString() }, (raw: unknown) => _decodeT93(raw));
  }

  countNftsByHolder(holder: HolderRef): Promise<bigint> {
    return this._view("count-nfts-by-holder", { "holder": (holder).toRaw() }, (raw: unknown) => BigInt(raw as string));
  }

  getAttributes(nftId: string): Promise<Array<Attribute>> {
    return this._view("get-attributes", { "nft-id": nftId }, (raw: unknown) => _decodeT88(raw));
  }

  getAttribute(nftId: string, key: string): Promise<string | null> {
    return this._view("get-attribute", { "nft-id": nftId, "key": key }, (raw: unknown) => _decodeT94(raw));
  }

}
