// Generated by kontor-codegen. Do not edit by hand.
import { Wit, ContractBase, type ContractAddress, type Inst, type KontorSession, Decimal, HolderRef, Attachment } from "@kontor/sdk";

export type Error = { kind: "message"; value: string } | { kind: "overflow"; value: string } | { kind: "div-by-zero"; value: string } | { kind: "syntax"; value: string } | { kind: "validation"; value: string };

export type Balance = {
  acc: HolderRef;
  amt: Decimal;
};

export type Transfer = {
  src: HolderRef;
  dst: HolderRef;
  amt: Decimal;
};

export type Burn = {
  src: HolderRef;
  amt: Decimal;
};

export type Mint = {
  dst: HolderRef;
  amt: Decimal;
};

const WIT = String.raw`package root:component;

world root {
  include kontor:built-in/built-in;
  use kontor:built-in/context.{core-context, view-context, proc-context, signer, holder-ref, contract};
  use kontor:built-in/error.{error};
  use kontor:built-in/numbers.{decimal};

  record balance {
    acc: holder-ref,
    amt: decimal,
  }

  record transfer {
    src: holder-ref,
    dst: holder-ref,
    amt: decimal,
  }

  record burn {
    src: holder-ref,
    amt: decimal,
  }

  record mint {
    dst: holder-ref,
    amt: decimal,
  }

  export issuance: async func(ctx: borrow<core-context>, amt: decimal) -> result<mint, error>;
  export issue-to: async func(ctx: borrow<core-context>, dst: holder-ref, amt: decimal) -> result<mint, error>;
  export hold: async func(ctx: borrow<core-context>, amt: decimal) -> result<transfer, error>;
  export release: async func(ctx: borrow<core-context>, burn-amt: decimal) -> result<burn, error>;

  export init: async func(ctx: borrow<proc-context>) -> contract;

  export mint: async func(ctx: borrow<proc-context>, amt: decimal) -> result<mint, error>;
  export burn: async func(ctx: borrow<proc-context>, amt: decimal) -> result<burn, error>;
  export transfer: async func(ctx: borrow<proc-context>, dst: holder-ref, amt: decimal) -> result<transfer, error>;
  export balance: async func(ctx: borrow<view-context>, acc: holder-ref) -> option<decimal>;
  export balances: async func(ctx: borrow<view-context>) -> list<balance>;
  export total-supply: async func(ctx: borrow<view-context>) -> decimal;
  export attach: async func(ctx: borrow<proc-context>, vout: u32, amt: decimal) -> result<transfer, error>;
  export detach: async func(ctx: borrow<proc-context>) -> result<transfer, error>;
}
`;
const _wit = new Wit(WIT);

function _encodeError(v: Error): unknown { switch (v.kind) { case "message": return { kind: "message", value: (v as any).value }; case "overflow": return { kind: "overflow", value: (v as any).value }; case "div-by-zero": return { kind: "div-by-zero", value: (v as any).value }; case "syntax": return { kind: "syntax", value: (v as any).value }; case "validation": return { kind: "validation", value: (v as any).value }; default: throw new Error("unknown variant case: " + (v as any).kind); } }
function _decodeError(v: unknown): Error { switch ((v as any).kind) { case "message": return { kind: "message", value: (v as any).value } as Error; case "overflow": return { kind: "overflow", value: (v as any).value } as Error; case "div-by-zero": return { kind: "div-by-zero", value: (v as any).value } as Error; case "syntax": return { kind: "syntax", value: (v as any).value } as Error; case "validation": return { kind: "validation", value: (v as any).value } as Error; default: throw new Error("unknown variant case: " + (v as any).kind); } }
function _encodeBalance(v: Balance): unknown { return { "acc": (v.acc).toRaw(), "amt": (v.amt).toRaw() }; }
function _decodeBalance(v: unknown): Balance { return { acc: HolderRef.fromRaw((v as any)["acc"] as any), amt: Decimal.fromRaw((v as any)["amt"] as any) }; }
function _encodeTransfer(v: Transfer): unknown { return { "src": (v.src).toRaw(), "dst": (v.dst).toRaw(), "amt": (v.amt).toRaw() }; }
function _decodeTransfer(v: unknown): Transfer { return { src: HolderRef.fromRaw((v as any)["src"] as any), dst: HolderRef.fromRaw((v as any)["dst"] as any), amt: Decimal.fromRaw((v as any)["amt"] as any) }; }
function _encodeBurn(v: Burn): unknown { return { "src": (v.src).toRaw(), "amt": (v.amt).toRaw() }; }
function _decodeBurn(v: unknown): Burn { return { src: HolderRef.fromRaw((v as any)["src"] as any), amt: Decimal.fromRaw((v as any)["amt"] as any) }; }
function _encodeMint(v: Mint): unknown { return { "dst": (v.dst).toRaw(), "amt": (v.amt).toRaw() }; }
function _decodeMint(v: unknown): Mint { return { dst: HolderRef.fromRaw((v as any)["dst"] as any), amt: Decimal.fromRaw((v as any)["amt"] as any) }; }
function _encodeT91(v: { kind: "ok"; value: Mint } | { kind: "err"; value: Error }): unknown { return v.kind === "ok" ? { kind: "ok", value: _encodeMint(v.value) } : { kind: "err", value: _encodeError(v.value) }; }
function _decodeT91(v: unknown): { kind: "ok"; value: Mint } | { kind: "err"; value: Error } { return (v as any).kind === "ok" ? { kind: "ok" as const, value: _decodeMint((v as any).value) } : { kind: "err" as const, value: _decodeError((v as any).value) }; }
function _encodeT92(v: { kind: "ok"; value: Transfer } | { kind: "err"; value: Error }): unknown { return v.kind === "ok" ? { kind: "ok", value: _encodeTransfer(v.value) } : { kind: "err", value: _encodeError(v.value) }; }
function _decodeT92(v: unknown): { kind: "ok"; value: Transfer } | { kind: "err"; value: Error } { return (v as any).kind === "ok" ? { kind: "ok" as const, value: _decodeTransfer((v as any).value) } : { kind: "err" as const, value: _decodeError((v as any).value) }; }
function _encodeT93(v: { kind: "ok"; value: Burn } | { kind: "err"; value: Error }): unknown { return v.kind === "ok" ? { kind: "ok", value: _encodeBurn(v.value) } : { kind: "err", value: _encodeError(v.value) }; }
function _decodeT93(v: unknown): { kind: "ok"; value: Burn } | { kind: "err"; value: Error } { return (v as any).kind === "ok" ? { kind: "ok" as const, value: _decodeBurn((v as any).value) } : { kind: "err" as const, value: _decodeError((v as any).value) }; }
function _encodeT96(v: Decimal | null): unknown { return v == null ? null : (v).toRaw(); }
function _decodeT96(v: unknown): Decimal | null { return v == null ? null : Decimal.fromRaw(v as any); }
function _encodeT97(v: Array<Balance>): unknown { return v.map(x => _encodeBalance(x)); }
function _decodeT97(v: unknown): Array<Balance> { return (v as unknown[]).map(x => _decodeBalance(x)); }
function _encodeT98(v: unknown): unknown { return v; }
function _decodeT98(v: unknown): unknown { return v as unknown; }

export class Contract extends ContractBase {
  constructor(session: KontorSession, address: ContractAddress) {
    super(session, address, _wit);
  }

  issuance(amt: Decimal): Inst<{ kind: "ok"; value: Mint } | { kind: "err"; value: Error }> {
    return this._proc("issuance", { "amt": (amt).toRaw() }, (raw: unknown) => _decodeT91(raw));
  }

  issueTo(dst: HolderRef, amt: Decimal): Inst<{ kind: "ok"; value: Mint } | { kind: "err"; value: Error }> {
    return this._proc("issue-to", { "dst": (dst).toRaw(), "amt": (amt).toRaw() }, (raw: unknown) => _decodeT91(raw));
  }

  hold(amt: Decimal): Inst<{ kind: "ok"; value: Transfer } | { kind: "err"; value: Error }> {
    return this._proc("hold", { "amt": (amt).toRaw() }, (raw: unknown) => _decodeT92(raw));
  }

  release(burnAmt: Decimal): Inst<{ kind: "ok"; value: Burn } | { kind: "err"; value: Error }> {
    return this._proc("release", { "burn-amt": (burnAmt).toRaw() }, (raw: unknown) => _decodeT93(raw));
  }

  init(): Inst<unknown> {
    return this._proc("init", {  }, (raw: unknown) => _decodeT98(raw));
  }

  mint(amt: Decimal): Inst<{ kind: "ok"; value: Mint } | { kind: "err"; value: Error }> {
    return this._proc("mint", { "amt": (amt).toRaw() }, (raw: unknown) => _decodeT91(raw));
  }

  burn(amt: Decimal): Inst<{ kind: "ok"; value: Burn } | { kind: "err"; value: Error }> {
    return this._proc("burn", { "amt": (amt).toRaw() }, (raw: unknown) => _decodeT93(raw));
  }

  transfer(dst: HolderRef, amt: Decimal): Inst<{ kind: "ok"; value: Transfer } | { kind: "err"; value: Error }> {
    return this._proc("transfer", { "dst": (dst).toRaw(), "amt": (amt).toRaw() }, (raw: unknown) => _decodeT92(raw));
  }

  balance(acc: HolderRef): Promise<Decimal | null> {
    return this._view("balance", { "acc": (acc).toRaw() }, (raw: unknown) => _decodeT96(raw));
  }

  balances(): Promise<Array<Balance>> {
    return this._view("balances", {  }, (raw: unknown) => _decodeT97(raw));
  }

  totalSupply(): Promise<Decimal> {
    return this._view("total-supply", {  }, (raw: unknown) => Decimal.fromRaw(raw as any));
  }

  attachment(amt: Decimal): Attachment<{ kind: "ok"; value: Transfer } | { kind: "err"; value: Error }> {
    return this._attachment(
      "attach", { "vout": 0, "amt": (amt).toRaw() },
      "detach", {  },
      (raw: unknown) => _decodeT92(raw),
    );
  }

}
