const { withAndroidManifest } = require("@expo/config-plugins");

/**
 * Force `android:allowBackup="false"` on the application.
 *
 * A wallet must never let its private data be pulled off-device through the backup
 * channel — Android Auto Backup (Google Drive), `adb backup`, or device-to-device
 * transfer. The raw key + recovery phrase live in expo-secure-store, whose own
 * config plugin already excludes its store from backup; flipping the app-wide flag
 * off is the unambiguous belt-and-braces so nothing this app writes can ever leave
 * the device that way, regardless of what a future dependency starts persisting.
 *
 * Lives as a config plugin (not a hand-edit) because `android/` is generated by
 * `expo prebuild` (Continuous Native Generation) and is gitignored — a manual edit
 * to AndroidManifest.xml would be wiped on the next prebuild. Referenced from
 * app.json's `plugins` array.
 */
const withAndroidSecurity = (config) =>
  withAndroidManifest(config, (cfg) => {
    const application = cfg.modResults.manifest.application?.[0];
    if (application) {
      application.$["android:allowBackup"] = "false";
    }
    return cfg;
  });

module.exports = withAndroidSecurity;
