const { withProjectBuildGradle } = require("@expo/config-plugins");

/**
 * Link @kontor/sdk-native's Android adapter for 16 KB memory pages.
 *
 * Google Play rejects apps whose native libraries don't support 16 KB pages.
 * In 0.3.0-rc.6 the prebuilt Rust core (libkontor_sdk_native.so) is fine, but
 * the JNI/JSI adapter (libkontor-sdk-native.so) is compiled from the package's
 * CMakeLists.txt during our Gradle build. NDK r27 still links at 4 KB by
 * default, and React Native's Gradle plugin passes
 * -DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON only to the app's own CMake
 * project, never to a library's. This adds the flag to that one module.
 *
 * TEMPORARY: fixed upstream in KontorProtocol/Kontor#563. Delete this plugin
 * (and its app.json entry) once @kontor/sdk-native ships that fix.
 *
 * Lives as a config plugin because `android/` is generated by `expo prebuild`
 * and gitignored, and EAS installs the package fresh from npm, so neither a
 * hand-edit nor a node_modules patch would reach a cloud build.
 */
const MARKER = "// @kontor-16kb-page-size";

const SNIPPET = `
${MARKER}
subprojects { project ->
  if (project.name == "kontor_sdk-native") {
    def addFlag = {
      project.android.defaultConfig.externalNativeBuild.cmake.arguments "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
    }
    if (project.state.executed) {
      addFlag()
    } else {
      project.afterEvaluate { addFlag() }
    }
  }
}
`;

const withKontorPageSize = (config) =>
  withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") {
      throw new Error("withKontorPageSize: expected a Groovy android/build.gradle");
    }
    if (!cfg.modResults.contents.includes(MARKER)) {
      cfg.modResults.contents += SNIPPET;
    }
    return cfg;
  });

module.exports = withKontorPageSize;
