const { withGradleProperties } = require("@expo/config-plugins");

/**
 * Raise the Gradle daemon's Metaspace (and heap) ceiling.
 *
 * Release builds run `lintVitalRelease`, which analyzes every module — including
 * third-party ones such as react-native-screens. Android lint loads Kotlin
 * "symbol light classes" in-process in the Gradle daemon; on a large Kotlin
 * module that blows past the default 256–512m Metaspace cap and dies with
 * `OutOfMemoryError: Metaspace`, failing
 * `:react-native-screens:lintVitalAnalyzeRelease` (Metaspace is class-metadata
 * memory, separate from the `-Xmx` heap — more heap alone does not help). Giving
 * the daemon a larger Metaspace ceiling fixes it directly while keeping lint on.
 *
 * Lives as a config plugin because `android/` is generated by `expo prebuild`
 * (Continuous Native Generation) and is gitignored — a hand-edit to
 * gradle.properties would be wiped on the next prebuild. Referenced from
 * app.json's `plugins` array.
 */
const JVM_ARGS = "-Xmx4096m -XX:MaxMetaspaceSize=2048m";

const withGradleMemory = (config) =>
  withGradleProperties(config, (cfg) => {
    const existing = cfg.modResults.find(
      (item) => item.type === "property" && item.key === "org.gradle.jvmargs",
    );
    if (existing) {
      existing.value = JVM_ARGS;
    } else {
      cfg.modResults.push({
        type: "property",
        key: "org.gradle.jvmargs",
        value: JVM_ARGS,
      });
    }
    return cfg;
  });

module.exports = withGradleMemory;
